public class Kata {
  /*
  If you finish this kata, you can try Insane Coloured Triangles by Bubbler, which is a much harder version of this one.
  A coloured triangle is created from a row of colours, each of which is red, green or blue. Successive rows, each containing one fewer colour than the last, are generated by considering the two touching colours in the previous row. If these colours are identical, the same colour is used in the new row. If they are different, the missing colour is used in the new row. This is continued until the final row, with only a single colour, is generated.
  The different possibilities are:

  The different possibilities are:
  Colour here:        G G        B G        R G        B R
  Becomes colour:      G          R          B          G

  With a bigger example:
  R R G B R G B B
   R B R G B R B
    G G B R G G
     G R G B G
      B B R R
       B G R
        R B
         G
  */
  public char triangle(final String row) {
    int rr = row.length();
        String str[] = new String[rr];
        for (int i = 0; i < row.length(); i++) {
            str[i] = String.valueOf(row.charAt(i));
        }
        while (rr >= 1) {
            String str1[] = new String[rr - 1];
            
            for (int i = 0; i < str1.length; i++) {
                
                if (str[i].equals(str[i+1])) {
                    str1[i] = str[i];
                } else if ((str[i].charAt(0) == 'R' && str[i+1].charAt(0) == 'G') || (str[i+1].charAt(0) == 'R' && str[i].charAt(0) == 'G')) {
                    str1[i] = String.valueOf('B');
                } else if ((str[i].charAt(0) == 'R' && str[i+1].charAt(0) == 'B') || (str[i+1].charAt(0) == 'R' && str[i].charAt(0) == 'B')) {
                    str1[i] = String.valueOf('G');
                } else if ((str[i].charAt(0) == 'G' && str[i+1].charAt(0) == 'B') || (str[i+1].charAt(0) == 'G' && str[i].charAt(0) == 'B')) {
                    str1[i] = String.valueOf('R');
                }
                System.out.print(str1[i]);
            }
            System.out.println("");
            for (int i = 0; i < rr - 1; i++) {
                str[i] = str1[i];
            }
            rr--;
        }
        return str[0].charAt(0);
  }
}
